### ISSUE TITLE
Sunrise & sunset is not in UTC

### ISSUE THREAD

**Issue by PaulMaly** [bhdouglass/weather-man#2]
Please, give ability to get initial timestamp values from data service.

**Comment by bhdouglass** [comment]
Thanks for the suggestion, I'll look into getting this feature included.

**Comment by PaulMaly** [comment]
Thanks! And also it would be nice if initial weather service response will be somehow available too. For example:

`result.getFullResponse()`

Your formatting features are great, but sometimes we need to have an access to not formatted data.

**Comment by bhdouglass** [comment]
I thought about this some more, and it seems unnecessary. You can always use `result.getSunriseDate()` to get a javascript Date and manipulate it as you please.
